POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{"title": "Hello world!", "author": "oliver", "url": "https://blog.com", "likes": "10"}
###
GET http://localhost:3003/api/blogs HTTP/1.1